[pytest]
testpaths = tests
log_cli = true
log_cli_level = INFO

markers =
    smoke: critical API tests
    regression: complete API regression tests
    distributed: tests against containerized service versions